version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27717:27017
    hostname: mongo
    environment:
      - MONGO_INITDB_DATABASE=userdb
    networks:
      - shared-net

  java:
    container_name: java
    build:
      context: ./
    ports:
      - 8090:8090
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge