spring:
  profiles:
    active: dev

server:
  port : 8090

gitHub:
  users:
    base-url: https://api.github.com/users
    user-path: /{user}
    filter:
      publicReposCount: 10
      followersCount: 5
      createdDate: "01/01/05"

app:
  data-fetch:
    fixed-delay: 3600000
    page-size: 6
    start: 0
    count: 5

springdoc:
  swagger-ui:
    path: /docs/swagger-ui
  api-docs:
    path: /docs/api-docs
  paths-to-match: /api/v1/**

sec:
  jwt:
    signing-key: strongkey
    claim-name: scopes
    expiration: 86400000
    token-prefix: Bearer